[package]
name = "lyra-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
lyra-core = { path = "../lyra-core" }
thiserror = { workspace = true }
serde = { workspace = true }
bitflags = "2"

[dev-dependencies]
lyra-parser = { path = "../lyra-parser" }
