[package]
name = "lyra"
version = "0.1.0"
edition = "2021"
authors = ["Parker Gabel"]
description = "A symbolic computation engine inspired by Wolfram Language"
license = "MIT"

[[bin]]
name = "lyra"
path = "src/main.rs"


[[bin]]
name = "lyra-pkg"
path = "src/pkg_main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rustyline = "13.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
ndarray = "0.16"
rand = "0.8"
rand_distr = "0.4"
dashmap = "6.1"
rayon = "1.10"
toml = "0.8"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
parking_lot = "0.12"
crossbeam = "0.8"
crossbeam-channel = "0.5"
crossbeam-deque = "0.8"
crossbeam-utils = "0.8"
once_cell = "1.19"
num_cpus = "1.16"
# Serialization dependencies
# Networking dependencies
reqwest = { version = "0.11", features = ["json", "stream", "cookies", "multipart"] }
petgraph = "0.6"
url = "2.5"
uuid = { version = "1.8", features = ["v4"] }
# Web scraping and parsing
scraper = "0.17"
# Cloud storage dependencies (lightweight implementation)
bytes = "1.5"
# String processing dependencies
regex = "1.10"
base64 = "0.22"
html-escape = "0.2"
percent-encoding = "2.3"
# Data processing dependencies
csv = "1.3"
jsonpath_lib = "0.3"
# Date/time dependencies
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.8"
# Developer tools dependencies
log = "0.4"
env_logger = "0.10"
colored = "2.0"
# System integration dependencies
sysinfo = "0.29"
which = "4.4"
dirs = "5.0"
# Cryptographic dependencies
ring = "0.17"
hex = "0.4"
# Documentation system dependencies
fuzzy-matcher = "0.3"
# AI/ML Integration dependencies (Phase 14A)
# Vector operations
nalgebra = "0.33"
# Text processing
unicode-segmentation = "1.10"
# HTTP client for APIs (already have reqwest)
# serde_json already included above

# MLOps dependencies (Phase 14B)
# Data processing and validation
polars = { version = "0.33", features = ["lazy", "temporal", "strings"] }
# Statistical analysis
statrs = "0.16"
# SQLite for local storage
rusqlite = { version = "0.30", features = ["bundled", "chrono"] }
# Additional serialization for MLOps

# Phase 15A: Database Integration Dependencies
# SQL databases
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "mysql", "sqlite", "chrono", "uuid", "json"] }

# NoSQL databases
mongodb = "2.8"
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Graph databases

# Schema and migration

# Data formats and serialization (using compatible versions)
# Commenting out for now due to version conflicts
# parquet = "49.0"
# arrow = "49.0"

# Connection pooling
deadpool = "0.10"

# Additional utilities
futures-util = "0.3"

# Phase 15B: Advanced Analytics & Statistics Dependencies
# Additional numerical libraries for analytics

# Phase 16A: Streaming & Event-Driven Architecture Dependencies
# Apache Kafka (commented out due to cmake requirement)
# rdkafka = { version = "0.36", features = ["cmake-build", "libz", "ssl", "sasl"] }

# Message queues (commented out to avoid compilation issues)
# lapin = "2.3"  # RabbitMQ
# redis already included above with additional features

# WebSocket and real-time
axum = { version = "0.7", features = ["ws", "macros"] }

# gRPC (commented out to avoid compilation issues)
# tonic = "0.10"
# prost = "0.12"

# Event sourcing
# event-store = { git = "https://github.com/EventStore/EventStore-Client-Rust" }

# Stream processing

# Additional serialization (bincode already included)

# Phase 16B: Production Observability & Monitoring Dependencies
# OpenTelemetry and tracing
opentelemetry = { version = "0.21", features = ["trace", "metrics"] }
tracing = "0.1"

# Metrics and monitoring (prometheus already included above)
# sysinfo already included above

# Profiling and debugging

# Alerting and notifications (reqwest already included)
# slack-api = "0.25"  # Slack integration (commented out due to package name issue)

# Time series and storage

# Phase 17A: Data Visualization & Dashboards Dependencies
# Chart rendering
plotters = { version = "0.3", features = ["all_series", "svg_backend", "bitmap_backend"] }

# Interactive visualization
wasm-bindgen = "0.2"

# Image processing

# PDF generation
printpdf = "0.6"

# Template rendering
tera = "1.19"
# serde_json already included above

# Color management
palette = "0.7"

# Phase 17B: Advanced System Integrations Dependencies
# Git integration

# CI/CD platform integration (using compatible HTTP clients)
# Using reqwest for API calls instead of platform-specific libraries to avoid conflicts

# Process execution for CI/CD scripts
# which = "4.4"  # Already included above

# Cost optimization and cloud pricing APIs
# Using reqwest for cloud API calls

[dev-dependencies]
insta = { version = "1.34", features = ["yaml"] }
pretty_assertions = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.0"
futures = "0.3"

[lib]
name = "lyra"
path = "src/lib.rs"

[[bench]]
name = "lyra_benchmarks"
harness = false

[[bench]]
name = "rule_ordering_benchmarks"
harness = false

[[bench]]
name = "type_system_benchmarks"
harness = false

[[bench]]
name = "advanced_memory_benchmarks"
harness = false

[[bench]]
name = "concurrency_benchmarks"
harness = false

[[bench]]
name = "serialization_benchmarks"
harness = false

[[bench]]
name = "performance_validation"
harness = false

[[bench]]
name = "speedup_claims_validation"
harness = false

[[bench]]
name = "regression_detection"
harness = false

[[bench]]
name = "async_performance_benchmarks"
harness = false

[[bench]]
name = "micro_benchmarks"
harness = false

[[bench]]
name = "workload_simulations"
harness = false

[[bench]]
name = "memory_profiling"
harness = false

[[bench]]
name = "phase3b_performance_validation"
harness = false

[[bench]]
name = "automated_performance_monitor"
harness = false

