[package]
name = "lyra"
version = "0.1.0"
edition = "2021"
authors = ["Parker Gabel"]
description = "A symbolic computation engine inspired by Wolfram Language"
license = "MIT"

[[bin]]
name = "lyra"
path = "src/main.rs"

[[bin]]
name = "debug_test"
path = "debug_test.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rustyline = "13.0"
nom = "7.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
ndarray = "0.16"
rand = "0.8"
dashmap = "6.1"
rayon = "1.10"
toml = "0.8"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
parking_lot = "0.12"
crossbeam = "0.8"
crossbeam-channel = "0.5"
crossbeam-deque = "0.8"
crossbeam-utils = "0.8"
flume = "0.11"
once_cell = "1.19"
num_cpus = "1.16"
# Serialization dependencies
rkyv = "0.8"
postcard = { version = "1.0", features = ["alloc"] }
memmap2 = "0.9"
lz4_flex = "0.11"
zstd = "0.13"
bincode = "1.3"
byteorder = "1.5"
rmp-serde = "1.1"
flate2 = "1.0"
core_affinity = "0.8"
hwloc2 = "2.1"

[dev-dependencies]
insta = { version = "1.34", features = ["yaml"] }
pretty_assertions = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.0"
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }

[lib]
name = "lyra"
path = "src/lib.rs"

[[bench]]
name = "lyra_benchmarks"
harness = false

[[bench]]
name = "rule_ordering_benchmarks"
harness = false

[[bench]]
name = "type_system_benchmarks"
harness = false

[[bench]]
name = "advanced_memory_benchmarks"
harness = false

[[bench]]
name = "concurrency_benchmarks"
harness = false

[[bench]]
name = "serialization_benchmarks"
harness = false

[[bench]]
name = "performance_validation"
harness = false

[[bench]]
name = "speedup_claims_validation"
harness = false

[[bench]]
name = "regression_detection"
harness = false

[[bench]]
name = "async_performance_benchmarks"
harness = false

[[bench]]
name = "micro_benchmarks"
harness = false

[[bench]]
name = "workload_simulations"
harness = false

[[bench]]
name = "memory_profiling"
harness = false

[[bench]]
name = "phase3b_performance_validation"
harness = false

[[bench]]
name = "automated_performance_monitor"
harness = false