[package]
name = "lyra"
version = "0.1.0"
edition = "2021"
authors = ["Parker Gabel"]
description = "A symbolic computation engine inspired by Wolfram Language"
license = "MIT"

[[bin]]
name = "lyra"
path = "src/main.rs"

[[bin]]
name = "debug_test"
path = "debug_test.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rustyline = "13.0"
nom = "7.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
ndarray = "0.16"
rand = "0.8"
dashmap = "6.1"
rayon = "1.10"

[dev-dependencies]
insta = { version = "1.34", features = ["yaml"] }
pretty_assertions = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }

[lib]
name = "lyra"
path = "src/lib.rs"

[[bench]]
name = "lyra_benchmarks"
harness = false

[[bench]]
name = "rule_ordering_benchmarks"
harness = false