edition = "2021"
max_width = 100
use_field_init_shorthand = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
wrap_comments = true
imports_granularity = "Crate"
newline_style = "Unix"
use_small_heuristics = "Max"