[package]
name = "lyra-stdlib"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
lyra-runtime = { path = "../lyra-runtime" }
lyra-core = { path = "../lyra-core" }
lyra-parser = { path = "../lyra-parser" }

[features]
default = ["core", "string", "math", "list", "assoc", "logic", "concurrency", "schema", "explain", "tools"]
core = []
string = []
math = []
list = []
assoc = []
logic = []
concurrency = []
schema = []
explain = []
tools = []
testing = []
simd_kernels = []
big-real-rug = ["rug"]

[dependencies.rug]
optional = true
version = "1"
