[alias]
fmt-check = "fmt -- --check"
clippy-all = "clippy --all-targets --all-features -- -D warnings"
min-rt = "build -p lyra-runtime --no-default-features"
min-stdlib = "build -p lyra-stdlib --no-default-features -F logic -F list"
